import{S as b,a as M,i as L}from"./assets/vendor-mj6yH6lW.js";(function(){const s=document.createElement("link").relList;if(s&&s.supports&&s.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))l(t);new MutationObserver(t=>{for(const r of t)if(r.type==="childList")for(const a of r.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&l(a)}).observe(document,{childList:!0,subtree:!0});function i(t){const r={};return t.integrity&&(r.integrity=t.integrity),t.referrerPolicy&&(r.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?r.credentials="include":t.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function l(t){if(t.ep)return;t.ep=!0;const r=i(t);fetch(t.href,r)}})();const o={gallery:document.querySelector(".gallery"),loader:document.querySelector(".loader"),showMore:document.querySelector("[data-showMore]"),form:document.querySelector(".form")},v=new b(".gallery a",{navText:["←","→"],captionsData:"alt",captionDelay:"250"});function f(e){const s=e.map(({webformatURL:i,largeImageURL:l,tags:t,likes:r,views:a,comments:g,downloads:w})=>`
         <li class="card">
              <a href="${l}">
                <img src="${i}" alt="${t}" />
            <ul class="img-info">
               <li class="text"><span class="bold">Likes</span>${r}</li>
               <li class="text"><span class="bold">Views</span>${a}</li>
               <li class="text"><span class="bold">Comments</span>${g}</li>
               <li class="text"><span class="bold">Downloads</span>${w}</li>
            </ul>
            </a>
        </li>
            `).join("");o.gallery.insertAdjacentHTML("beforeend",s),v.refresh()}function E(){o.gallery.innerHTML=""}function h(){o.loader.style.display="block"}function d(){o.loader.style.display="none"}function x(){o.showMore.classList.remove("visually-hidden")}function p(){o.showMore.classList.add("visually-hidden")}async function m(e,s){return(await M.get("https://pixabay.com/api/",{params:{key:"49667356-c9b78f361687dff4f3855c0b0",q:e,image_type:"photo",orientation:"horizontal",safesearch:!0,page:s,per_page:15}})).data}function u(e){L.show({title:`${e}`,titleColor:"white",messageColor:"white",backgroundColor:"red",position:"topRight"})}o.form.addEventListener("submit",q);o.showMore.addEventListener("click",$);let n=1,c="";const S=15;function q(e){if(e.preventDefault(),c=this.elements["search-text"].value.trim(),D(),!c){u("Enter correct data, please");return}P()}async function P(){h();try{const e=await m(c,n);O(e.totalHits),f(e.hits),y(e)}catch(e){if(e.message==="no item")return;u(e.message)}finally{d()}}async function $(){p(),h(),n++,o.showMore.disabled=!0;try{const e=await m(c,n);f(e.hits),o.showMore.disabled=!1,y(e),k()}catch(e){u(e.message)}finally{d()}}function D(){p(),E(),n=1,o.form.reset()}function O(e){if(!e)throw u("Sorry, there are no images matching your search query. Please try again!"),d(),new Error("no item")}function y(e){if(Math.ceil(e.totalHits/S)===n){showError("We're sorry, but you've reached the end of search results.","0e9c79");return}x()}function k(){const e=o.gallery.firstElementChild.getBoundingClientRect().height;window.scrollBy({top:e*2,behavior:"smooth"})}
//# sourceMappingURL=index.js.map
